[manager]
show_hidden = true
[[opener.edit]]
run = 'lvim "$@"'
block = true
for = "unix"
[plugin]
prepend_previewers = [
    # markdown previewer
    { name = "*.md", run = "glow" },
    # Archive previewer
    { mime = "application/*zip",            run = "ouch" },
    { mime = "application/x-tar",           run = "ouch" },
    { mime = "application/x-bzip2",         run = "ouch" },
    { mime = "application/x-7z-compressed", run = "ouch" },
    { mime = "application/x-rar",           run = "ouch" },
    { mime = "application/x-xz",            run = "ouch" },
]
[preview]
max_width = 1000
max_height = 1000

[[plugin.prepend_fetchers]]
id   = "git"
name = "*"
run  = "git"

[[plugin.prepend_fetchers]]
id   = "git"
name = "*/"
run  = "git"
